<ApplicationFile>
     <FileHeader>
         <FormatVersion>2.0</FormatVersion>
         <Sender>NESFDC</Sender>
         <CreationDate>2024-04-24</CreationDate>
         <CreationTime>10:11:06</CreationTime>
         <Number>99993</Number>
         <Institution>0002</Institution>
         </FileHeader>
     <ApplicationsList>
         <#list data as record>
         <Application>
             <RegNumber>AA_OnBoard_C7_${record.REG_NUMBER}</RegNumber>
             <Institution>0002</Institution>
             <InstitutionIDType>Branch</InstitutionIDType>
             <OrderDprt>0102</OrderDprt>
             <ObjectType>Contract</ObjectType>
             <ActionType>Update</ActionType>
             <ObjectFor>
                 <ContractIDT>
                     <ContractNumber>${record.N_PAYM}</ContractNumber>
                     </ContractIDT>
                 </ObjectFor>
             <SubApplList>
                  <Application>
                      <RegNumber>AA_OnBoard_${record.REG_NUMBER}</RegNumber>
                      <ObjectType>ContractCounterparty</ObjectType>
                      <ActionType>AddOrUpdate</ActionType>
                      <Data>
                          <Counterparty>
                              <Code>ACQ2</Code>
                              <Name>SECOND IBAN</Name>
                              <PaymentCode>NXS</PaymentCode>
                              <ContractNumber>${record.IBAN}</ContractNumber>
                              <MemberId>BIC</MemberId>
                              <PartyType>Counterparty</PartyType>
                              <Client>
                                  <ClientInfo>
                                      <RegNumber>${record.CONTACT_CODE}</RegNumber>
                                      </ClientInfo>
                                  <RefContractNumber>${record.N_PAYM}</RefContractNumber>
                                  </Client>
                              </Counterparty>
                          </Data>
                      </Application>
                  <Application>
                      <RegNumber>AA_OnBoard_C1_${record.REG_NUMBER}</RegNumber>
                      <ObjectType>ContractParameter</ObjectType>
                      <ActionType>AddOrUpdate</ActionType>
                      <Data>
                          <CustomerParameters>
                              <Parameter>
                                  <Code>W4O_PAYM_ATTR</Code>
                                  <Value>ACQ2</Value>
                                  </Parameter>
                              </CustomerParameters>
                          </Data>
                      </Application>
                  </SubApplList>
              </Application>
              </#list>
          </ApplicationsList>
     </ApplicationFile>
